name: ⚒️ Task
description: Create a development task
projects: ["cartesian-io/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating this task. Please include as much detail as possible.
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Include any relevant background information required for the ticket. Include any links to existing requirements documents, ADRs, etc.
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Describe what should be done as part of the ticket.
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution
      description: Include any possible solutions that should be considered as part of the ticket. Include any links to documents, relevant code files in GitHub, etc.
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define the “Definition of Done”.
    validations:
      required: true
